import assert from "node:assert/strict";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import { createSparkPiParitySlashCommands } from "../apps/spark-tui/src/cli/pi-parity-commands.ts";
import {
  BUILTIN_SPARK_THEMES,
  SparkSessionStore,
  renderSparkTranscriptHtml,
  type SparkCliHostServices,
} from "../apps/spark-tui/src/host/index.ts";
import type {
  SparkNativeMessage,
  SparkNativeSlashCommandContext,
} from "../apps/spark-tui/src/native-tui.ts";

void test("renderSparkTranscriptHtml is self-contained, theme-aware, and escapes transcript content", () => {
  const html = renderSparkTranscriptHtml({
    title: "Unsafe transcript",
    cwd: "/tmp/project",
    sessionId: "session:test",
    theme: BUILTIN_SPARK_THEMES[0],
    messages: [
      {
        role: "assistant",
        text: '<script>alert("x")</script> & <b>bold</b>',
        details: { provider: "fake" },
      },
    ],
  });

  assert.match(html, /Spark Dark/);
  assert.match(html, /--assistant: #7dd3fc/);
  assert.match(
    html,
    /&lt;script&gt;alert\(&quot;x&quot;\)&lt;\/script&gt; &amp; &lt;b&gt;bold&lt;\/b&gt;/,
  );
  assert.doesNotMatch(html, /<script>alert/);
  assert.doesNotMatch(html, /src="https?:/);
});

void test("/export html and /share write safe local HTML for visible and persisted Spark sessions", async () => {
  const dir = await mkdtemp(join(tmpdir(), "spark-html-export-"));
  try {
    const store = new SparkSessionStore({
      cwd: dir,
      sessionsRoot: join(dir, ".spark", "sessions"),
    });
    const services = {
      cwd: dir,
      sessionStore: store,
      theme: BUILTIN_SPARK_THEMES[1],
      config: { extensions: [], providers: [] },
      diagnostics: [],
    } as unknown as SparkCliHostServices;
    const commands = createSparkPiParitySlashCommands(services);
    const messages: SparkNativeMessage[] = [
      { role: "system", text: "hidden", display: false },
      { role: "user", text: "please export <danger>" },
      { role: "assistant", text: "exported & safe" },
      { role: "tool", toolName: "read", toolStatus: "success", text: "tool <result>" },
    ];
    const ctx = { session: { messages } } as SparkNativeSlashCommandContext;

    const visiblePath = join(dir, "visible.html");
    const visibleResult = await commands.export.handler(`html ${visiblePath}`, ctx);
    assert.equal(visibleResult, `Exported HTML: ${visiblePath}`);
    const visibleHtml = await readFile(visiblePath, "utf8");
    assert.match(visibleHtml, /Spark visible transcript/);
    assert.match(visibleHtml, /please export &lt;danger&gt;/);
    assert.match(visibleHtml, /tool:read/);
    assert.doesNotMatch(visibleHtml, /hidden/);

    const record = store.createSession({ id: "persisted-html" });
    store.appendMessage(record, {
      role: "user",
      content: "persisted <unsafe>",
      timestamp: Date.now(),
    });
    store.appendMessage(record, {
      role: "assistant",
      content: [{ type: "text", text: "persisted reply" }],
      timestamp: Date.now(),
      provider: "fake-provider",
      model: "fake-model",
    });
    await store.save(record);

    const persistedPath = join(dir, "persisted.html");
    const persistedResult = await commands.export.handler(
      `html persisted-html ${persistedPath}`,
      ctx,
    );
    assert.equal(persistedResult, `Exported HTML: ${persistedPath}`);
    const persistedHtml = await readFile(persistedPath, "utf8");
    assert.match(persistedHtml, /session: persisted-html/);
    assert.match(persistedHtml, /persisted &lt;unsafe&gt;/);
    assert.match(persistedHtml, /fake-provider/);

    const sharePath = join(dir, "share.html");
    const shareResult = await commands.share.handler(sharePath, ctx);
    assert.match(
      String(shareResult),
      new RegExp(`Share-safe HTML export: ${escapeRegExp(sharePath)}`),
    );
    assert.match(String(shareResult), /No external upload was performed/);
    const shareHtml = await readFile(sharePath, "utf8");
    assert.match(shareHtml, /Generated by Spark native TUI/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
