[default]
extend-ignore-words-re = ["^[a-zA-Z]{1,3}$"]
extend-ignore-re = [
  "(?Rm)^.*(#|//)\\s*typos:\\s*disable-line$",
  "(?s)(#|//)\\s*typos:\\s*off.*?\\n\\s*(#|//)\\s*typos:\\s*on",
]

[default.extend-words]
agentic = "agentic"
earendil = "earendil"
spark-md = "spark-md"
sixbones = "sixbones"
unsupport = "unsupport"
typebox = "typebox"

[files]
extend-exclude = [
  ".spark/**",
  "**/.pi-lens/**",
  "packages/spark-i18n/src/paraglide/**"
]
