packages:
  - "packages/*"

allowBuilds:
  "@google/genai": true
  koffi: true
  protobufjs: true

catalog:
  vite: "npm:@voidzero-dev/vite-plus-core@0.1.18"
  vite-plus: "0.1.18"
  vitest: "npm:@voidzero-dev/vite-plus-test@0.1.18"

overrides:
  vite: "catalog:"
  vite-plus: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowedVersions:
    typescript: "*"
    vite: "*"
    vitest: "*"
