import {
  Activity,
  Archive,
  Bell,
  Bot,
  Box,
  Check,
  ChevronDown,
  ChevronRight,
  Copy,
  Folder,
  GitBranch,
  Home,
  Inbox,
  LogOut,
  MessageSquareText,
  PackageOpen,
  PanelsTopLeft,
  Play,
  Plus,
  Search,
  Settings,
  Sparkles,
  TriangleAlert,
  type LucideIcon,
} from "@lucide/svelte";

export const iconMap = {
  activity: Activity,
  agents: Bot,
  archive: Archive,
  artifacts: Box,
  bell: Bell,
  check: Check,
  chevron: ChevronRight,
  "chevron-down": ChevronDown,
  copy: Copy,
  cube: PackageOpen,
  folder: Folder,
  home: Home,
  inbox: Inbox,
  logout: LogOut,
  play: Play,
  plus: Plus,
  repos: GitBranch,
  search: Search,
  settings: Settings,
  spark: Sparkles,
  workspace: PanelsTopLeft,
  warning: TriangleAlert,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;

export const fallbackIcon = MessageSquareText;
