import {
  Activity,
  Archive,
  Bell,
  Bot,
  Box,
  Check,
  ChevronDown,
  ChevronRight,
  Copy,
  Folder,
  GitBranch,
  Hash,
  Home,
  Inbox,
  LogOut,
  Menu,
  MessageCircle,
  MessageSquarePlus,
  MessageSquareText,
  PackageOpen,
  PanelsTopLeft,
  Play,
  Plus,
  Search,
  Send,
  Settings,
  Sparkles,
  TriangleAlert,
  UserRound,
  UsersRound,
  Waves,
  X,
  type LucideIcon,
} from "@lucide/svelte";

export const iconMap = {
  activity: Activity,
  agents: Bot,
  archive: Archive,
  artifacts: Box,
  bell: Bell,
  check: Check,
  chevron: ChevronRight,
  "chevron-down": ChevronDown,
  copy: Copy,
  cube: PackageOpen,
  folder: Folder,
  hash: Hash,
  home: Home,
  inbox: Inbox,
  logout: LogOut,
  menu: Menu,
  message: MessageCircle,
  "new-message": MessageSquarePlus,
  play: Play,
  plus: Plus,
  repos: GitBranch,
  search: Search,
  send: Send,
  settings: Settings,
  spark: Sparkles,
  workspace: PanelsTopLeft,
  warning: TriangleAlert,
  user: UserRound,
  users: UsersRound,
  waves: Waves,
  close: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;

export const fallbackIcon = MessageSquareText;
