/** Compaction surface for the native TUI host. */

export type {
  SparkCompactionTokenSource,
  SparkCompactionFallbackReason,
  SparkCompactModelSelection,
  SparkCompactionSettings,
} from "./types.ts";
export {
  CURRENT_SPARK_COMPACTION_SUMMARY_VERSION,
  DEFAULT_SPARK_COMPACTION_SETTINGS,
} from "./types.ts";

export {
  normalizeSparkCompactionOutcomeMetadata,
  meterSparkContextTokens,
  parseSparkSmartCompactionSummary,
  parseSparkSmartCompactionModelOutput,
  renderSparkSmartCompactionPrompt,
  renderSparkSmartCompactionSummary,
  smartSparkCompactionSummary,
  smartSparkCompactionSummaryWithFallback,
  shouldSparkMicroCompact,
  microCompactSparkMessages,
  scheduleSparkCompaction,
  shouldSparkCompact,
  estimateSparkTokens,
  estimateSparkContextTokens,
  findSparkCompactionCutPoint,
  findSparkTurnStartIndex,
  prepareSparkCompaction,
  compactSparkSessionRecord,
  compactSparkVisibleTranscript,
  deterministicSparkCompactionSummary,
  appendSparkBranchSummary,
  navigateSparkSessionBranchWithSummary,
  collectSparkBranchEntriesToSummarize,
  entriesToMessages,
  type SparkContextUsageEstimate,
  type SparkTokenMeterInput,
  type SparkCutPointResult,
  type SparkCompactionPreparation,
  type SparkSmartCompactionSummary,
  type SparkCompactionSummaryResult,
  type SparkSmartCompactionModelRequest,
  type SparkSmartCompactionModelRunner,
  type SparkCompactionSummarizer,
  type SparkSmartCompactionAttempt,
  type SparkCompactionPassType,
  type SparkCompactionScheduleResult,
  type SparkMicroCompactionResult,
  type SparkTranscriptMessageForCompaction,
  type SparkVisibleTranscriptCompactionResult,
  type SparkBranchNavigationSummaryResult,
} from "./algorithm.ts";
