/** @deprecated Import path preserved — implementation lives in ./compaction/. */
export {
  CURRENT_SPARK_COMPACTION_SUMMARY_VERSION,
  DEFAULT_SPARK_COMPACTION_SETTINGS,
  normalizeSparkCompactionOutcomeMetadata,
  meterSparkContextTokens,
  parseSparkSmartCompactionSummary,
  parseSparkSmartCompactionModelOutput,
  renderSparkSmartCompactionPrompt,
  renderSparkSmartCompactionSummary,
  smartSparkCompactionSummary,
  smartSparkCompactionSummaryWithFallback,
  shouldSparkMicroCompact,
  microCompactSparkMessages,
  scheduleSparkCompaction,
  shouldSparkCompact,
  estimateSparkTokens,
  estimateSparkContextTokens,
  findSparkCompactionCutPoint,
  findSparkTurnStartIndex,
  prepareSparkCompaction,
  compactSparkSessionRecord,
  compactSparkVisibleTranscript,
  deterministicSparkCompactionSummary,
  appendSparkBranchSummary,
  navigateSparkSessionBranchWithSummary,
  collectSparkBranchEntriesToSummarize,
  entriesToMessages,
  type SparkCompactionTokenSource,
  type SparkCompactionFallbackReason,
  type SparkCompactModelSelection,
  type SparkCompactionSettings,
  type SparkContextUsageEstimate,
  type SparkTokenMeterInput,
  type SparkCutPointResult,
  type SparkCompactionPreparation,
  type SparkSmartCompactionSummary,
  type SparkCompactionSummaryResult,
  type SparkSmartCompactionModelRequest,
  type SparkSmartCompactionModelRunner,
  type SparkCompactionSummarizer,
  type SparkSmartCompactionAttempt,
  type SparkCompactionPassType,
  type SparkCompactionScheduleResult,
  type SparkMicroCompactionResult,
  type SparkTranscriptMessageForCompaction,
  type SparkVisibleTranscriptCompactionResult,
  type SparkBranchNavigationSummaryResult,
} from "./compaction/index.ts";
