import { mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, isAbsolute, join, resolve } from "node:path";

import type { SparkTheme } from "./theme.ts";
import type {
  SparkBranchSummaryEntry,
  SparkCompactionEntry,
  SparkCustomMessageEntry,
  SparkSessionEntry,
  SparkSessionMessage,
  SparkSessionMessageEntry,
  SparkSessionRecord,
} from "./session-store.ts";

export interface SparkHtmlTranscriptMessage {
  role: string;
  text: string;
  timestamp?: string;
  label?: string;
  details?: Record<string, unknown>;
}

export interface SparkHtmlExportInput {
  title: string;
  cwd: string;
  sessionId?: string;
  generatedAt?: string;
  messages: readonly SparkHtmlTranscriptMessage[];
  theme?: SparkTheme;
}

export interface SparkHtmlWriteOptions {
  outputPath?: string;
  cwd: string;
  sparkHome?: string;
  kind?: "export" | "share";
  filenameStem?: string;
}

export interface SparkHtmlWriteResult {
  path: string;
  html: string;
}

export function renderSparkTranscriptHtml(input: SparkHtmlExportInput): string {
  const theme = input.theme;
  const colors = theme?.colors ?? fallbackHtmlColors(input.theme?.mode ?? "dark");
  const mode = theme?.mode ?? "dark";
  const generatedAt = input.generatedAt ?? new Date().toISOString();
  const messages = input.messages.filter((message) => message.text.trim().length > 0);
  return `<!doctype html>
<html lang="en" data-theme="${escapeHtml(theme?.id ?? mode)}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(input.title)}</title>
<style>
:root {
  color-scheme: ${mode};
  --fg: ${cssColor(colors.foreground)};
  --muted: ${cssColor(colors.muted)};
  --border: ${cssColor(colors.border)};
  --accent: ${cssColor(colors.accent)};
  --user: ${cssColor(colors.user)};
  --assistant: ${cssColor(colors.assistant)};
  --system: ${cssColor(colors.system)};
  --tool: ${cssColor(colors.tool)};
  --thinking: ${cssColor(colors.thinking)};
  --custom: ${cssColor(colors.custom)};
  --bg: ${mode === "light" ? "#f8fafc" : "#0f172a"};
  --panel: ${mode === "light" ? "#ffffff" : "#111827"};
  --code-bg: ${mode === "light" ? "#f1f5f9" : "#1f2937"};
}
* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--fg); font: 15px/1.5 ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
main { max-width: 980px; margin: 0 auto; padding: 32px 20px 56px; }
header { border: 1px solid var(--border); background: var(--panel); border-radius: 14px; padding: 18px 20px; margin-bottom: 18px; }
h1 { margin: 0 0 8px; font-size: 1.35rem; }
.meta { color: var(--muted); font-size: .9rem; overflow-wrap: anywhere; }
.message { border: 1px solid var(--border); border-left: 5px solid var(--accent); background: var(--panel); border-radius: 12px; padding: 14px 16px; margin: 12px 0; }
.message[data-role="user"] { border-left-color: var(--user); }
.message[data-role="assistant"] { border-left-color: var(--assistant); }
.message[data-role="system"] { border-left-color: var(--system); }
.message[data-role="tool"] { border-left-color: var(--tool); }
.message[data-role="thinking"] { border-left-color: var(--thinking); }
.message[data-role="custom"] { border-left-color: var(--custom); }
.role { display: flex; gap: 10px; align-items: baseline; color: var(--muted); font-size: .85rem; text-transform: uppercase; letter-spacing: .04em; margin-bottom: 8px; }
.role strong { color: var(--fg); }
.content { margin: 0; white-space: pre-wrap; overflow-wrap: anywhere; font: inherit; }
.details { margin-top: 10px; color: var(--muted); background: var(--code-bg); border-radius: 8px; padding: 8px; overflow-x: auto; }
.empty { color: var(--muted); font-style: italic; }
footer { margin-top: 24px; color: var(--muted); font-size: .85rem; }
</style>
</head>
<body>
<main>
<header>
<h1>${escapeHtml(input.title)}</h1>
<div class="meta">cwd: ${escapeHtml(input.cwd)}</div>
${input.sessionId ? `<div class="meta">session: ${escapeHtml(input.sessionId)}</div>` : ""}
<div class="meta">generated: ${escapeHtml(generatedAt)}</div>
${theme ? `<div class="meta">theme: ${escapeHtml(theme.label)} (${escapeHtml(theme.id)})</div>` : ""}
</header>
${messages.length === 0 ? '<p class="empty">No visible transcript messages.</p>' : messages.map(renderHtmlMessage).join("\n")}
<footer>Generated by Spark native TUI. Content is escaped and no external scripts or network uploads are embedded.</footer>
</main>
</body>
</html>
`;
}

export function sparkSessionRecordToHtmlMessages(
  record: SparkSessionRecord,
): SparkHtmlTranscriptMessage[] {
  return record.entries.map(sparkSessionEntryToHtmlMessage).filter(isDefined);
}

export async function writeSparkTranscriptHtml(
  input: SparkHtmlExportInput,
  options: SparkHtmlWriteOptions,
): Promise<SparkHtmlWriteResult> {
  const html = renderSparkTranscriptHtml(input);
  const outputPath = resolveHtmlOutputPath(options);
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, html, "utf8");
  return { path: outputPath, html };
}

export function defaultSparkHtmlExportDir(sparkHome?: string): string {
  return join(defaultSparkHtmlRoot(sparkHome), "exports");
}

export function defaultSparkShareDir(sparkHome?: string): string {
  return join(defaultSparkHtmlRoot(sparkHome), "share");
}

function renderHtmlMessage(message: SparkHtmlTranscriptMessage): string {
  const role = normalizeHtmlRole(message.role);
  const label = message.label ?? message.role;
  const timestamp = message.timestamp ? `<span>${escapeHtml(message.timestamp)}</span>` : "";
  const details = message.details
    ? `<pre class="details">${escapeHtml(JSON.stringify(message.details, null, 2))}</pre>`
    : "";
  return `<article class="message" data-role="${escapeHtml(role)}">
<div class="role"><strong>${escapeHtml(label)}</strong>${timestamp}</div>
<pre class="content">${escapeHtml(message.text)}</pre>${details}
</article>`;
}

function sparkSessionEntryToHtmlMessage(
  entry: SparkSessionEntry,
): SparkHtmlTranscriptMessage | undefined {
  if (entry.type === "message") {
    const message = (entry as SparkSessionMessageEntry).message;
    return {
      role: normalizeSessionRole(message.role),
      label: message.role,
      text: sparkSessionMessageText(message),
      timestamp: entry.timestamp,
      details: safeDetails(message),
    };
  }
  if (entry.type === "compaction") {
    const compaction = entry as SparkCompactionEntry;
    return {
      role: "custom",
      label: "compaction",
      text: compaction.summary,
      timestamp: entry.timestamp,
      details: {
        firstKeptEntryId: compaction.firstKeptEntryId,
        tokensBefore: compaction.tokensBefore,
      },
    };
  }
  if (entry.type === "branch_summary") {
    const summary = entry as SparkBranchSummaryEntry;
    return {
      role: "custom",
      label: "branch summary",
      text: summary.summary,
      timestamp: entry.timestamp,
      details: { fromId: summary.fromId },
    };
  }
  if (entry.type === "custom_message") {
    const custom = entry as SparkCustomMessageEntry;
    if (!custom.display) return undefined;
    return {
      role: "custom",
      label: custom.customType,
      text: customContentText(custom.content),
      timestamp: entry.timestamp,
      details: custom.details as Record<string, unknown> | undefined,
    };
  }
  if (entry.type === "model_change") {
    return {
      role: "system",
      label: "model",
      text: `${entry.provider}/${entry.modelId}`,
      timestamp: entry.timestamp,
    };
  }
  if (entry.type === "thinking_level_change") {
    return {
      role: "system",
      label: "thinking",
      text: entry.thinkingLevel,
      timestamp: entry.timestamp,
    };
  }
  if (entry.type === "session_info") {
    return {
      role: "system",
      label: "session info",
      text: entry.name ?? "session info",
      timestamp: entry.timestamp,
    };
  }
  return undefined;
}

function sparkSessionMessageText(message: SparkSessionMessage): string {
  const content = message.content;
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return JSON.stringify(content ?? "");
  return content.map(contentBlockText).filter(Boolean).join("\n");
}

function customContentText(content: SparkCustomMessageEntry["content"]): string {
  if (typeof content === "string") return content;
  return content.map(contentBlockText).filter(Boolean).join("\n");
}

function contentBlockText(block: unknown): string {
  if (!block || typeof block !== "object") return "";
  const record = block as Record<string, unknown>;
  if (record.type === "text" && typeof record.text === "string") return record.text;
  if (record.type === "thinking" && typeof record.thinking === "string") return record.thinking;
  if (record.type === "image") return "[image]";
  if (record.type === "toolCall") {
    const name = typeof record.name === "string" ? record.name : "tool";
    return `[tool call: ${name}]`;
  }
  return "";
}

function safeDetails(message: SparkSessionMessage): Record<string, unknown> | undefined {
  const details: Record<string, unknown> = {};
  if (typeof message.provider === "string") details.provider = message.provider;
  if (typeof message.model === "string") details.model = message.model;
  return Object.keys(details).length ? details : undefined;
}

function resolveHtmlOutputPath(options: SparkHtmlWriteOptions): string {
  if (options.outputPath) return resolvePath(options.outputPath, options.cwd);
  const root =
    options.kind === "share"
      ? defaultSparkShareDir(options.sparkHome)
      : defaultSparkHtmlExportDir(options.sparkHome);
  const stem = sanitizeFileStem(options.filenameStem ?? `spark-${options.kind ?? "export"}`);
  return join(root, `${stem}.html`);
}

function defaultSparkHtmlRoot(sparkHome?: string): string {
  return sparkHome ?? process.env.SPARK_HOME ?? join(homedir(), ".spark");
}

function resolvePath(path: string, cwd: string): string {
  if (path === "~") return homedir();
  if (path.startsWith("~/")) return join(homedir(), path.slice(2));
  return isAbsolute(path) ? path : resolve(cwd, path);
}

function sanitizeFileStem(value: string): string {
  return (
    value
      .trim()
      .replace(/[^a-z0-9._-]+/giu, "-")
      .replace(/^-+|-+$/gu, "") || `spark-export-${Date.now().toString(36)}`
  );
}

function normalizeSessionRole(role: string): string {
  if (role === "toolResult") return "tool";
  return role;
}

function normalizeHtmlRole(role: string): string {
  if (role === "user" || role === "assistant" || role === "system") return role;
  if (role === "tool" || role === "thinking" || role === "custom") return role;
  return "custom";
}

function cssColor(value: string): string {
  return /^#[0-9a-f]{6}$/iu.test(value) ? value : "#d4d4d8";
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/gu, "&amp;")
    .replace(/</gu, "&lt;")
    .replace(/>/gu, "&gt;")
    .replace(/"/gu, "&quot;")
    .replace(/'/gu, "&#39;");
}

function fallbackHtmlColors(mode: "dark" | "light") {
  return {
    foreground: mode === "light" ? "#18181b" : "#d4d4d8",
    muted: mode === "light" ? "#71717a" : "#8b949e",
    border: mode === "light" ? "#a1a1aa" : "#52525b",
    accent: mode === "light" ? "#0369a1" : "#7dd3fc",
    user: mode === "light" ? "#4338ca" : "#a5b4fc",
    assistant: mode === "light" ? "#0369a1" : "#7dd3fc",
    system: mode === "light" ? "#18181b" : "#d4d4d8",
    tool: mode === "light" ? "#6d28d9" : "#c4b5fd",
    thinking: mode === "light" ? "#a21caf" : "#f0abfc",
    custom: mode === "light" ? "#be185d" : "#f9a8d4",
  };
}

function isDefined<T>(value: T | undefined): value is T {
  return value !== undefined;
}
