/** @deprecated Import path preserved — implementation lives in ./session-store/. */
export {
  CURRENT_SPARK_SESSION_VERSION,
  SparkSessionStore,
  defaultSparkSessionsRoot,
  defaultSparkHome,
  workspaceSessionHash,
  parseSparkSessionEntries,
  writeJsonLinesAtomically,
  type SparkSessionHeader,
  type SparkSessionEntryBase,
  type SparkSessionMessage,
  type SparkSessionMessageEntry,
  type SparkThinkingLevelChangeEntry,
  type SparkModelChangeEntry,
  type SparkCompactionOutcomeMetadata,
  type SparkCompactionEntry,
  type SparkBranchSummaryEntry,
  type SparkCustomEntry,
  type SparkCustomMessageEntry,
  type SparkLabelEntry,
  type SparkSessionInfoEntry,
  type SparkSessionEntry,
  type SparkSessionFileEntry,
  type SparkSessionRecord,
  type SparkSessionInfo,
  type SparkSessionStoreOptions,
  type NewSparkSessionOptions,
} from "./session-store/index.ts";
